name: CI
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Клонируем репозиторий

    - name: Set up Python
      uses: actions/setup-python@v4  # Устанавливаем Python
      with:
        python-version: '3.10'  # Указываем версию Python

    - name: Run flake8 (linting) # Устанавливаем и запускаем линтинг
      run: |
        pip install pylint 
        
    - name: Run tests with pytest # Устанавливаем pytest и запускаем тесты
      run: | 
        pip install pytest   
        pytest 

  auto-merge:
    runs-on: ubuntu-latest
    needs: build  # Этот шаг запускается только после успешного прохождения тестов
    steps:
      - name: Auto-merge PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          merge-method: squash  # Может быть: merge, squash, rebase
          github-token: ${{ secrets.GITHUB_TOKEN }}  # Токен для доступа к API
